---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exit-node.fullname" . }}-env
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
  {{- with .Values.tailscaleState.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
stringData:
  {{- with .Values.loginServer.value }}
  TS_LOGIN_SERVER: {{ . | quote }}
  {{- end}}
  {{- with .Values.preAuthKey.value }}
  TS_AUTHKEY: {{ . | quote }}
  {{- end }}
  TS_ROUTES: "0.0.0.0/0,::/0"
  TG_WEBUI_PORT: "8080"
  TS_HOSTNAME: {{ .Release.Name }}
  TG_NAMESERVERS: 9.9.9.9,149.112.112.112,2620:fe::fe,2620:fe::9
{{- if eq .Values.tailscaleState.type "Secret" }}
  TS_KUBE_SECRET: {{ include "exit-node.tailscaleState" . }}
{{- end }}
{{- if .Values.tsMgrConfig }}
  TS_MANAGER_CONFIG_PATH: /etc/wireguard/ts-manager.yaml
{{- end }}
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.36.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "exit-node.fullname" . }}-wireguard
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "exit-node.labels" . | nindent 4 }}
  {{- with .Values.tailscaleState.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  wg0.conf: |-
   {{ .Values.wireguardConfig | b64enc }}
  {{- if .Values.tsMgrConfig }}
  ts-manager.yaml: |-
    {{ .Values.tsMgrConfig | b64enc }}
  {{- end }}
